# Header
menu:
  Home: /
  Archives: /archives
  Tag: /tags
  Github: https://github.com/yonmy
rss: /atom.xml

# Content
excerpt_link: More...
fancybox: true

# Miscellaneous
google_analytics:
favicon: /favicon.png

# Copyright Infomation
startyear: 2016
