# Header
menu:
  Home: /
  Archives: /archives
  Tag: /tags
  Github: https://github.com/yonmy
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Miscellaneous
google_analytics: UA-121698823-2
favicon: /favicon.png

# Copyright Infomation
startyear: 2016
